# Generated by Django 2.2 on 2021-05-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
    ]
