# Generated by Django 2.2 on 2021-05-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_auto_20210515_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
